services:
  # PHP service
  php:
    build: 
      context: .
    volumes:
      - ./:/var/www/html
  
  # Web service
  web:
    image: nginx:1.27
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"